spring.application.name=Movie-Recommendation-App

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:5432/movie_app
spring.datasource.username=postgres
spring.datasource.password=nvd2526
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

tmdb.api-key=${TMDB_API_KEY}
tmdb.base-url=https://api.themoviedb.org/3

jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=864000000
jwt.header=Authorization
jwt.token-prefix=Bearer

recommendation.service.url=http://localhost:8000